name: update sharedlayer library on aws
on:
  push:
    branches:
    - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
    - name: Update To Latest Version
      run: curl --location --request POST 'https://4lhz7nq5cn3ojggwtfqa2g6q2a0psxso.lambda-url.us-east-1.on.aws/UpdateFunctionToLatestVersion' \--header 'Content-Type: application/json' \--data-raw '{    "function":{		"name": "lambdafunctions"	},	"layer":{		"name":"messageLibraryLayer",		"description":"",		"compatible_runtimes":["python3.9"],		"license_info":"",		"compatible_architectures":["x86_64"]	}}'
      shell: bash
      
